config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"

  get 'auth/reddit/callback', to: "sessions#create", as: "callback"
  get '/logout', to: 'sessions#destroy', as: 'logout'

  get '/noko', to: 'noko#grab_text'

  resources :users do
    resources :boards do
      resources :posts
    end
  end
end

app/models/board.rb
class Board < ActiveRecord::Base
  belongs_to :user
  has_many :posts

  validates :title, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :board
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :boards
  
  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.name = auth.info.name
      user.oauth_token = auth.credentials.token
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :can_modify?

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def can_modify?(user)
    current_user.id == user.id
  end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_user

  def index
    @boards = @user.boards.all

    respond_to do |format|
      format.html
      format.json { render json: @boards }
    end
  end

  def create
    @board = @user.boards.new(board_params)

    if can_modify?(@user) && @board.save
      render json: @board
    else
    end
  end

  def update
    @board = @user.boards.find(params[:id])

    if can_modify?(@user) && @board.update(board_params)
      render json: @board
    else
    end
  end

  def destroy
    @board = @user.boards.find(params[:id])

    if can_modify?(@user) && @board.destroy
      render json: @board
    else
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def board_params
    params.require(:board).permit(:title)
  end
end

app/controllers/noko_controller.rb
class NokoController < ApplicationController
  def grab_text
    client = RestClient.get(params[:url], user_agent: 'Chrome')
    noko_client = Nokogiri::HTML(client)
    body_text = noko_client.css(".usertext-body")[1]

    render text: body_text
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_user
  before_action :set_board

  def index
    @posts = @board.posts.all
    render json: @posts
  end

  def create
    @post = @board.posts.new(post_params)

    if can_modify?(@user) && @post.save
      render json: @post
    else
    end
  end

  def update
    @post = @board.posts.find(params[:id])

    if can_modify?(@user) && @post.update(post_params)
      render json: @post
    else
    end
  end

  def destroy
    @post = @board.posts.find(params[:id])

    if can_modify?(@user) && @post.destroy
      render json: @post
    else
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def set_board
    @board = @user.boards.find(params[:board_id])
  end

  def post_params
    params.require(:post).permit(
      :title,
      :author,
      :score,
      :url,
      :subreddit,
      :selftext,
      :reddit_id,
      :media,
      :board_id,
      :thumbnail,
    )
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(user_params)
    session[:access_token] = request.env['omniauth.auth']['credentials']['token']
    session[:access_token_secret] = request.env['omniauth.auth']['credentials']['secret']
    session[:user_id] = user.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    User.from_omniauth(env["omniauth.auth"])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :set_user

  def index
    if current_user
      @boards = @user.boards.all
    end
  end

  private

  def set_user
    @user = current_user
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/boards/_boards.html.erb
<script id="add-board-template" type="text/x-handlebars-template">
  <div class="ui form add-board">
    <div class="field">
      <input type="text" name="some_name" value="" placeholder="Name">
    </div>
    <div class="ui green submit button board-create">
    <i class="checkmark icon"></i>
      Complete
    </div>
      <i class="big remove icon hide-form"></i>
  </div>
</script>

<script id="board-template" type="text/x-handlebars-template">
  <div class="ui card" data-boardId="{{id}}">
    <div class="content">
      <div class="header left floated">{{title}}</div>
    </div>
  </div>
</script>

<script id="board-edit-template" type="text/x-handlebars-template">
  <div class="ui form edit-board">
    <label class="edit-board-label">Title</label>
    <input type="text" value="{{boardTitle}}">
    <div class="ui green submit button board-update">
      <i class="checkmark icon"></i>
    </div>
  </div>
</script>

<script id="board-show-template" type="text/x-handlebars-template">
  <div class="ui modal board-show" data-boardId="{{boardId}}">
    <i class="close icon"></i>
    <div class="header">
      {{title}}
    </div>
    {{#each posts}}
      <div class="content ui vertical segment" data-postId="{{this.postId}}">
        <div class="ui small image">
          <img src="{{this.imageURL}}">
        </div>
        <div class="description">
          <div class="ui header"><span class="board-post-score">{{this.score}}
           | </span><a href="{{this.url}}" target="_blank">
           {{this.name}}</a></div>
              <p>posted by: <a href="http://reddit.com/u/{{this.author}}
              " target="_blank">{{this.author}}</a> to:
              <a href="http://reddit.com/r/{{this.subreddit}}" target="_blank">
              {{this.subreddit}}</a></p>
            <p>{{this.selftext}}</p>
        </div>
      </div>
    {{/each}}
  </div>
</script>

<script id="board-show-user-template" type="text/x-handlebars-template">
  <div class="ui modal board-show" data-boardId="{{boardId}}">
    <i class="close icon"></i>
    <div class="header">
      {{title}}
      <i class="remove icon delete"></i>
      <i class="edit icon update"></i>
    </div>
    {{#each posts}}
      <div class="content ui vertical segment" data-postId="{{this.postId}}">
        <div class="ui small image">
          <img src="{{this.imageURL}}">
        </div>
        <div class="description">
          <div class="ui header"><span class="board-post-score">{{this.score}}
           | </span><a href="{{this.url}}" target="_blank">
           {{this.name}}</a></div>
            <p>
              posted by: <a href="http://reddit.com/u/{{this.author}}" target="_blank">
              {{this.author}}</a> to:
              <a href="http://reddit.com/r/{{this.subreddit}}" target="_blank">
              {{this.subreddit}}</a>
            </p>
            <p>{{this.selftext}}</p>
          <div class="ui right floated red button post-delete">Delete</div>
        </div>
      </div>
    {{/each}}
  </div>
</script>

app/views/boards/index.html.erb
<div class="fourteen wide column centered boards-view" data-userId='<%= @user.id %>'>
  <div class="fourteen wide column centered row">
    <div class="four wide column boards-title"><span id="#username"><%= @user.name %></span>'s Boards</div>
    <div class="ten wide column"></div>
  </div>

  <div class="fourteen wide column centered row">
    <div class="ui fluid cards">
      <% @boards.each do |board| %>
        <div class="ui card" data-boardId="<%= board.id %>">
          <div class="content">
            <div class="header left floated"><%= board.title %></div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class='<%= current_user && can_modify?(@user) ? "modifiable" : "readable" %>'>
</div>

<%= render "boards" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoardIt</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
</head>
  <body class = "background">
    <div class="ui left vertical labeled inline icon sidebar menu">
      <a class="item" href="/">
        <i class="home icon"></i>
        Home
      </a>
      <% if current_user %>
        <a class="item" href="<%= user_boards_path(current_user) %>">
          <i class="book icon"></i>
          My Boards
        </a>
        <a class="item" href="/logout">
          <i class="sign out icon"></i>
          Log Out
        </a>
      <% else %>
        <a class="item" href="/auth/reddit">
          <i class="sign in icon"></i>
          Sign In
        </a>
      <% end %>
    </div>
    <div class="pusher">
      <div class="ui black big launch right attached fixed button menu-button">
        <i class="black content icon"></i>
        <span class="text">Menu</span>
      </div>

      <div class="ui icon right floated subreddit input">
        <input class="ui subreddit-input" type="text" placeholder="Search for a Subreddit" >
      </div>

      <span class="ui two wide column right floated icon button add-board-button">
        <i class="two plus icon"></i>
        Add Board
      </span>
      <div class="ui grid">
        <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/welcome/index.html.erb
      <div class="four wide column left-column">
      </div>

      <div class="eight wide column middle-column">
        <div class="eight wide column post-info">
          <div class="ui two column grid">
            <div class="three wide column">
              <div class="ui horizontal segment">
                <div class = "post-score"> </div>
              </div>
            </div>
            <div class="eleven wide column">
              <div class="ui vertical segment">
                <div class="caption"></div>
              </div>
              <div class="ui vertical segment">
                <div class = "subreddit-author author"> </div>
              </div>
            </div>
          </div>
        </div>

        <div class="ui segment contents"></div>

        <div class="ui button save-post">
          save
        </div>
        <a class="ui button post-comment" target="_blank">
          comments
        </a>
      </div>

      <div class="one wide column right-column">
        <div></div>
      </div>



    <% if current_user %>
      <div class="ui modal save">
        <div class="header" >
          <h2> Which board would you like to save to? </h2>
        <div class="ui search">
          <div class="ui icon input">
            <input class="prompt add-board" type="text" placeholder="Add a board">
            <i class="add circle icon"></i>
        </div>
      </div>
      </div>
        <div class="all-boards" data-userid = "<%= current_user.id  %>">
          <% @boards.each do |board| %>
            <div class="ui vertical segment single-board" data-boardid = "<%= board.id %>" >
              <h3 class = "board-title"><%= board.title %></h3>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="ui small save modal">
        <h2 class = "login-alert login-text"> Sign In! </h2>
        <a class="ui blue button login-button" href="auth/reddit">
          Login Here!
        </a>
      </div>
    <% end %>